# Generated by Django 6.0.5 on 2026-05-17 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Schools', '0004_nucleosgroup_created_at_nucleosgroup_deleted_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nucleosgroup',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='school',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='school',
            name='logo',
            field=models.ImageField(null=True, upload_to='logos'),
        ),
    ]
