# Generated by Django 6.0.5 on 2026-05-17 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Schools', '0005_alter_nucleosgroup_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nucleosgroup',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='school',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
