# Generated by Django 6.0.5 on 2026-05-11 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0005_remove_user_password_hash_alter_user_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='token',
            old_name='user_id',
            new_name='user',
        ),
    ]
