# Generated by Django 6.0.5 on 2026-05-15 13:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Schools', '0003_alter_nucleosgroup_id_alter_nucleosgroup_table'),
        ('Users', '0003_alter_coordinator_id_alter_director_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='director',
            name='school',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='Schools.school'),
        ),
    ]
