# Generated by Django 6.0.5 on 2026-05-17 23:12

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Schools', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classroom',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ('course', models.CharField(max_length=100)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                (
                    'deleted_at',
                    models.DateTimeField(blank=True, default=None, null=True),
                ),
                (
                    'school',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to='Schools.school',
                    ),
                ),
            ],
            options={
                'db_table': 'classroom',
            },
        ),
    ]
